### ISSUE TITLE
Read Error when loading AVL Input File

### ISSUE THREAD

**Issue by joyo44** [joanibal/pyAVL#29]
An issue occured when reading a geofile exported from AeroSandbox. AVL has no
problem to read the components.

The error message is:

GeoFile :  airplane.avl
Traceback (most recent call last):
  File "run_opt_Twist.py", line 92, in <module>
    prob.setup(mode='rev')
  File "/home/john/.local/lib/python3.8/site-packages/openmdao/core/problem.py", line 1031, in setup
    model._setup(model_comm, mode, self._metadata)
  File "/home/john/.local/lib/python3.8/site-packages/openmdao/core/group.py", line 735, in _setup
    self._setup_procs(self.pathname, comm, mode, self._problem_meta)
  File "/home/john/.local/lib/python3.8/site-packages/openmdao/core/group.py", line 640, in _setup_procs
    subsys._setup_procs(subsys.pathname, sub_comm, mode, prob_meta)
  File "/home/john/.local/lib/python3.8/site-packages/openmdao/core/group.py", line 585, in _setup_procs
    self.setup()
  File "/home/john/.local/lib/python3.8/site-packages/pyavl/om_wrapper.py", line 31, in setup
    avl = AVLSolver(geo_file=geom_file, mass_file=mass_file, debug=False)
  File "/home/john/.local/lib/python3.8/site-packages/pyavl/pyAVL.py", line 303, in __init__
    self._init_surf_data()
  File "/home/john/.local/lib/python3.8/site-packages/pyavl/pyAVL.py", line 334, in _init_surf_data
    raise RuntimeError("nasec is not the same for all sections")
RuntimeError: nasec is not the same for all sections
     Reading body shape from file: airplane.avl.fuse0

I've send you the related files by e-mail.

**Comment by joanibal** [comment]
Hey thanks for reporting this. It's on my todo list and I should be able to get to it Thursday evening or this weekend. Sorry for the delay.

**Comment by joanibal** [comment]
v1.6.2  should fix your issue. Reopen this if not
